name: Run cpplint

on:
  push:

jobs:
  build-runtimes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install cpplint
        run: |
          apt-get update
          apt-get install -y cpplint

      - name: Run linter
        run: find . -regex '.*\.\(cpp\|cc\|c\|h\|hpp\)' -exec cpplint {} +